---
- name: Install and configure WordPress
  hosts: Dev
  become: yes
  vars_files:
    - wp_vars.yml
    
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install PHP and required modules
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
        - php-xmlrpc
        - php-soap
        - php-intl
        - php-zip

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress archive
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Configure WordPress
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/wp-config.php"
      notify:
        - Restart Apache

         
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

